name: app_library
description: Tercen app library
version: 0.0.1
author: Alexandre Maurel <alexandre.maurel@gmail.com>
homepage: https://www.tercen.com

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  github:
  path:
